### ISSUE TITLE
マーカー画像がリンク切れする

### ISSUE THREAD

**Issue by inaniwaudon** [until-tsukuba/vendmap#23]
leaflet のマーカー画像がリンク切れ（`https://unpkg.com/leaflet@1.8.0/distmarker-icon-2x.png`）してしまっています。
ローカルの環境では発生しなかったので、vercel にデプロイしたときにだけ発生しているようです。

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/69859801/194772439-f4d2d657-30b4-462c-b490-22cacc3df3cd.png">

**Comment by eniehack** [comment]
leafletのバージョンが古過ぎる説がありますね
