### ISSUE TITLE
ブラウザがダークモードの際には地図のスタイルをダークモード寄りにしてほしい

### ISSUE THREAD

**Issue by oageo** [until-tsukuba/vendmap#48]
ダークモードを使用している際でも、使用しているスタイルが明るいため目にそこまで優しくない。

`window.matchMedia('(prefers-color-scheme: dark)').matches`などでダークモードを検知し、`+page.svelte`で読み込むスタイルを切り替え、目に優しくしてほしい。

**Comment by eniehack** [comment]
- [ ] freeで公開されているdarkmodeっぽいmap styleを探す

**Comment by eniehack** [comment]
cartoという会社が提供するdarkっぽいやつがあるので、それとデフォルトのやつを出し分ける実装をやる
optionalでdarkとlightの切り替えができるようにする（tailwindじゃないとやり方分かんないや
